/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AskRouteImport } from './routes/ask'
import { Route as ConfigureRouteImport } from './routes/configure'
import { Route as ConnectorsRouteImport } from './routes/connectors'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as EscalateRouteImport } from './routes/escalate'
import { Route as ItWorkRouteImport } from './routes/it-work'
import { Route as LeadershipRouteImport } from './routes/leadership'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MeetRouteImport } from './routes/meet'
import { Route as OfficeRouteImport } from './routes/office'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as WorksheetRouteImport } from './routes/worksheet'
import { Route as DeskItRouteImport } from './routes/desk/it'
import { Route as DeskRecordsRouteImport } from './routes/desk/records'
import { Route as KnowledgeIndexRouteImport } from './routes/knowledge/index'
import { Route as KnowledgeSlugRouteImport } from './routes/knowledge/$slug'
import { Route as RunbooksIndexRouteImport } from './routes/runbooks/index'
import { Route as RunbooksSlugRouteImport } from './routes/runbooks/$slug'
import { Route as TicketsIndexRouteImport } from './routes/tickets/index'
import { Route as TicketsTicketIdRouteImport } from './routes/tickets/$ticketId'
import { Route as TicketsNewRouteImport } from './routes/tickets/new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiPopuliWebhookRouteImport } from './routes/api/populi/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigureRoute = ConfigureRouteImport.update({
  id: '/configure',
  path: '/configure',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectorsRoute = ConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const EscalateRoute = EscalateRouteImport.update({
  id: '/escalate',
  path: '/escalate',
  getParentRoute: () => rootRouteImport,
} as any)
const ItWorkRoute = ItWorkRouteImport.update({
  id: '/it-work',
  path: '/it-work',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadershipRoute = LeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetRoute = MeetRouteImport.update({
  id: '/meet',
  path: '/meet',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeRoute = OfficeRouteImport.update({
  id: '/office',
  path: '/office',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksheetRoute = WorksheetRouteImport.update({
  id: '/worksheet',
  path: '/worksheet',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskItRoute = DeskItRouteImport.update({
  id: '/desk/it',
  path: '/desk/it',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRecordsRoute = DeskRecordsRouteImport.update({
  id: '/desk/records',
  path: '/desk/records',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeIndexRoute = KnowledgeIndexRouteImport.update({
  id: '/knowledge/',
  path: '/knowledge/',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeSlugRoute = KnowledgeSlugRouteImport.update({
  id: '/knowledge/$slug',
  path: '/knowledge/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RunbooksIndexRoute = RunbooksIndexRouteImport.update({
  id: '/runbooks/',
  path: '/runbooks/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunbooksSlugRoute = RunbooksSlugRouteImport.update({
  id: '/runbooks/$slug',
  path: '/runbooks/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsIndexRoute = TicketsIndexRouteImport.update({
  id: '/tickets/',
  path: '/tickets/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsTicketIdRoute = TicketsTicketIdRouteImport.update({
  id: '/tickets/$ticketId',
  path: '/tickets/$ticketId',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsNewRoute = TicketsNewRouteImport.update({
  id: '/tickets/new',
  path: '/tickets/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPopuliWebhookRoute = ApiPopuliWebhookRouteImport.update({
  id: '/api/populi/webhook',
  path: '/api/populi/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/configure': typeof ConfigureRoute
  '/connectors': typeof ConnectorsRoute
  '/directory': typeof DirectoryRoute
  '/escalate': typeof EscalateRoute
  '/it-work': typeof ItWorkRoute
  '/leadership': typeof LeadershipRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/meet': typeof MeetRoute
  '/office': typeof OfficeRoute
  '/ops': typeof OpsRoute
  '/reports': typeof ReportsRoute
  '/staff': typeof StaffRoute
  '/worksheet': typeof WorksheetRoute
  '/desk/it': typeof DeskItRoute
  '/desk/records': typeof DeskRecordsRoute
  '/knowledge/$slug': typeof KnowledgeSlugRoute
  '/runbooks/$slug': typeof RunbooksSlugRoute
  '/tickets/$ticketId': typeof TicketsTicketIdRoute
  '/tickets/new': typeof TicketsNewRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/runbooks/': typeof RunbooksIndexRoute
  '/tickets/': typeof TicketsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/populi/webhook': typeof ApiPopuliWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/configure': typeof ConfigureRoute
  '/connectors': typeof ConnectorsRoute
  '/directory': typeof DirectoryRoute
  '/escalate': typeof EscalateRoute
  '/it-work': typeof ItWorkRoute
  '/leadership': typeof LeadershipRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/meet': typeof MeetRoute
  '/office': typeof OfficeRoute
  '/ops': typeof OpsRoute
  '/reports': typeof ReportsRoute
  '/staff': typeof StaffRoute
  '/worksheet': typeof WorksheetRoute
  '/desk/it': typeof DeskItRoute
  '/desk/records': typeof DeskRecordsRoute
  '/knowledge/$slug': typeof KnowledgeSlugRoute
  '/runbooks/$slug': typeof RunbooksSlugRoute
  '/tickets/$ticketId': typeof TicketsTicketIdRoute
  '/tickets/new': typeof TicketsNewRoute
  '/knowledge': typeof KnowledgeIndexRoute
  '/runbooks': typeof RunbooksIndexRoute
  '/tickets': typeof TicketsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/populi/webhook': typeof ApiPopuliWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/configure': typeof ConfigureRoute
  '/connectors': typeof ConnectorsRoute
  '/directory': typeof DirectoryRoute
  '/escalate': typeof EscalateRoute
  '/it-work': typeof ItWorkRoute
  '/leadership': typeof LeadershipRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/meet': typeof MeetRoute
  '/office': typeof OfficeRoute
  '/ops': typeof OpsRoute
  '/reports': typeof ReportsRoute
  '/staff': typeof StaffRoute
  '/worksheet': typeof WorksheetRoute
  '/desk/it': typeof DeskItRoute
  '/desk/records': typeof DeskRecordsRoute
  '/knowledge/$slug': typeof KnowledgeSlugRoute
  '/runbooks/$slug': typeof RunbooksSlugRoute
  '/tickets/$ticketId': typeof TicketsTicketIdRoute
  '/tickets/new': typeof TicketsNewRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/runbooks/': typeof RunbooksIndexRoute
  '/tickets/': typeof TicketsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/populi/webhook': typeof ApiPopuliWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ask'
    | '/configure'
    | '/connectors'
    | '/directory'
    | '/escalate'
    | '/it-work'
    | '/leadership'
    | '/learn'
    | '/login'
    | '/meet'
    | '/office'
    | '/ops'
    | '/reports'
    | '/staff'
    | '/worksheet'
    | '/desk/it'
    | '/desk/records'
    | '/knowledge/$slug'
    | '/runbooks/$slug'
    | '/tickets/$ticketId'
    | '/tickets/new'
    | '/knowledge/'
    | '/runbooks/'
    | '/tickets/'
    | '/api/auth/$'
    | '/api/populi/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ask'
    | '/configure'
    | '/connectors'
    | '/directory'
    | '/escalate'
    | '/it-work'
    | '/leadership'
    | '/learn'
    | '/login'
    | '/meet'
    | '/office'
    | '/ops'
    | '/reports'
    | '/staff'
    | '/worksheet'
    | '/desk/it'
    | '/desk/records'
    | '/knowledge/$slug'
    | '/runbooks/$slug'
    | '/tickets/$ticketId'
    | '/tickets/new'
    | '/knowledge'
    | '/runbooks'
    | '/tickets'
    | '/api/auth/$'
    | '/api/populi/webhook'
  id:
    | '__root__'
    | '/'
    | '/ask'
    | '/configure'
    | '/connectors'
    | '/directory'
    | '/escalate'
    | '/it-work'
    | '/leadership'
    | '/learn'
    | '/login'
    | '/meet'
    | '/office'
    | '/ops'
    | '/reports'
    | '/staff'
    | '/worksheet'
    | '/desk/it'
    | '/desk/records'
    | '/knowledge/$slug'
    | '/runbooks/$slug'
    | '/tickets/$ticketId'
    | '/tickets/new'
    | '/knowledge/'
    | '/runbooks/'
    | '/tickets/'
    | '/api/auth/$'
    | '/api/populi/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AskRoute: typeof AskRoute
  ConfigureRoute: typeof ConfigureRoute
  ConnectorsRoute: typeof ConnectorsRoute
  DirectoryRoute: typeof DirectoryRoute
  EscalateRoute: typeof EscalateRoute
  ItWorkRoute: typeof ItWorkRoute
  LeadershipRoute: typeof LeadershipRoute
  LearnRoute: typeof LearnRoute
  LoginRoute: typeof LoginRoute
  MeetRoute: typeof MeetRoute
  OfficeRoute: typeof OfficeRoute
  OpsRoute: typeof OpsRoute
  ReportsRoute: typeof ReportsRoute
  StaffRoute: typeof StaffRoute
  WorksheetRoute: typeof WorksheetRoute
  DeskItRoute: typeof DeskItRoute
  DeskRecordsRoute: typeof DeskRecordsRoute
  KnowledgeSlugRoute: typeof KnowledgeSlugRoute
  RunbooksSlugRoute: typeof RunbooksSlugRoute
  TicketsTicketIdRoute: typeof TicketsTicketIdRoute
  TicketsNewRoute: typeof TicketsNewRoute
  KnowledgeIndexRoute: typeof KnowledgeIndexRoute
  RunbooksIndexRoute: typeof RunbooksIndexRoute
  TicketsIndexRoute: typeof TicketsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPopuliWebhookRoute: typeof ApiPopuliWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configure': {
      id: '/configure'
      path: '/configure'
      fullPath: '/configure'
      preLoaderRoute: typeof ConfigureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connectors': {
      id: '/connectors'
      path: '/connectors'
      fullPath: '/connectors'
      preLoaderRoute: typeof ConnectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escalate': {
      id: '/escalate'
      path: '/escalate'
      fullPath: '/escalate'
      preLoaderRoute: typeof EscalateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it-work': {
      id: '/it-work'
      path: '/it-work'
      fullPath: '/it-work'
      preLoaderRoute: typeof ItWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadership': {
      id: '/leadership'
      path: '/leadership'
      fullPath: '/leadership'
      preLoaderRoute: typeof LeadershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meet': {
      id: '/meet'
      path: '/meet'
      fullPath: '/meet'
      preLoaderRoute: typeof MeetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office': {
      id: '/office'
      path: '/office'
      fullPath: '/office'
      preLoaderRoute: typeof OfficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worksheet': {
      id: '/worksheet'
      path: '/worksheet'
      fullPath: '/worksheet'
      preLoaderRoute: typeof WorksheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk/it': {
      id: '/desk/it'
      path: '/desk/it'
      fullPath: '/desk/it'
      preLoaderRoute: typeof DeskItRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk/records': {
      id: '/desk/records'
      path: '/desk/records'
      fullPath: '/desk/records'
      preLoaderRoute: typeof DeskRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/': {
      id: '/knowledge/'
      path: '/knowledge'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof KnowledgeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/$slug': {
      id: '/knowledge/$slug'
      path: '/knowledge/$slug'
      fullPath: '/knowledge/$slug'
      preLoaderRoute: typeof KnowledgeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runbooks/': {
      id: '/runbooks/'
      path: '/runbooks'
      fullPath: '/runbooks/'
      preLoaderRoute: typeof RunbooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runbooks/$slug': {
      id: '/runbooks/$slug'
      path: '/runbooks/$slug'
      fullPath: '/runbooks/$slug'
      preLoaderRoute: typeof RunbooksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/': {
      id: '/tickets/'
      path: '/tickets'
      fullPath: '/tickets/'
      preLoaderRoute: typeof TicketsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/$ticketId': {
      id: '/tickets/$ticketId'
      path: '/tickets/$ticketId'
      fullPath: '/tickets/$ticketId'
      preLoaderRoute: typeof TicketsTicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/new': {
      id: '/tickets/new'
      path: '/tickets/new'
      fullPath: '/tickets/new'
      preLoaderRoute: typeof TicketsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/populi/webhook': {
      id: '/api/populi/webhook'
      path: '/api/populi/webhook'
      fullPath: '/api/populi/webhook'
      preLoaderRoute: typeof ApiPopuliWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AskRoute: AskRoute,
  ConfigureRoute: ConfigureRoute,
  ConnectorsRoute: ConnectorsRoute,
  DirectoryRoute: DirectoryRoute,
  EscalateRoute: EscalateRoute,
  ItWorkRoute: ItWorkRoute,
  LeadershipRoute: LeadershipRoute,
  LearnRoute: LearnRoute,
  LoginRoute: LoginRoute,
  MeetRoute: MeetRoute,
  OfficeRoute: OfficeRoute,
  OpsRoute: OpsRoute,
  ReportsRoute: ReportsRoute,
  StaffRoute: StaffRoute,
  WorksheetRoute: WorksheetRoute,
  DeskItRoute: DeskItRoute,
  DeskRecordsRoute: DeskRecordsRoute,
  KnowledgeSlugRoute: KnowledgeSlugRoute,
  RunbooksSlugRoute: RunbooksSlugRoute,
  TicketsTicketIdRoute: TicketsTicketIdRoute,
  TicketsNewRoute: TicketsNewRoute,
  KnowledgeIndexRoute: KnowledgeIndexRoute,
  RunbooksIndexRoute: RunbooksIndexRoute,
  TicketsIndexRoute: TicketsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPopuliWebhookRoute: ApiPopuliWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
